version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: aurum_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis-data:
