"""add_platform_fields_and_platform_scecific_id

Revision ID: 27b3b194bc5b
Revises: 6a2eac3e8152
Create Date: 2025-11-24 22:51:40.182218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27b3b194bc5b'
down_revision: Union[str, Sequence[str], None] = '6a2eac3e8152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Agregar nuevos campos a la tabla platforms
    op.add_column('platforms', sa.Column('display_name', sa.String(length=128), nullable=False, server_default=''))
    op.add_column('platforms', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('platforms', sa.Column('supported_asset_types', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('platforms', sa.Column('api_config', sa.JSON(), nullable=True))
    op.add_column('platforms', sa.Column('icon', sa.String(length=255), nullable=True))
    
    # Agregar campo platform_specific_id a investments
    op.add_column('investments', sa.Column('platform_specific_id', sa.String(length=255), nullable=True))
    
    # Crear índice para platform_specific_id
    op.create_index(op.f('ix_investments_platform_specific_id'), 'investments', ['platform_specific_id'], unique=False)
    
    # Actualizar display_name con los valores de name existentes
    op.execute("UPDATE platforms SET display_name = name")
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Eliminar índice de platform_specific_id
    op.drop_index(op.f('ix_investments_platform_specific_id'), table_name='investments')
    
    # Eliminar campo platform_specific_id de investments
    op.drop_column('investments', 'platform_specific_id')
    
    # Eliminar campos de platforms
    op.drop_column('platforms', 'icon')
    op.drop_column('platforms', 'api_config')
    op.drop_column('platforms', 'supported_asset_types')
    op.drop_column('platforms', 'is_active')
    op.drop_column('platforms', 'display_name')
    
    # ### end Alembic commands ###