"""add role column to users

Revision ID: 27f24bf5619d
Revises: 
Create Date: 2025-10-24 15:03:13.216090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f24bf5619d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('refresh_tokens', 'revoked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    # Add role column as nullable first
    op.add_column('users', sa.Column('role', sa.Enum('admin', 'analyst', 'investor', 'support', name='userrole'), nullable=True))
    # Set default value for existing users
    op.execute("UPDATE users SET role = 'investor' WHERE role IS NULL")
    # Make column NOT NULL
    op.alter_column('users', 'role', nullable=False)
    # Convert auth_provider to enum with USING clause
    op.alter_column('users', 'auth_provider',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('local', 'google', 'apple', name='authproviderenum'),
               nullable=False,
               postgresql_using='auth_provider::authproviderenum')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'auth_provider',
               existing_type=sa.Enum('local', 'google', 'apple', name='authproviderenum'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'role')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.alter_column('refresh_tokens', 'revoked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
