"""Add notes column to investments

Revision ID: 6a2eac3e8152
Revises: b7f9c974dddf
Create Date: 2025-11-24 17:30:20.564908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a2eac3e8152'
down_revision: Union[str, Sequence[str], None] = 'b7f9c974dddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investments_coingecko_id'))
        batch_op.drop_index(batch_op.f('ix_investments_id'))
        batch_op.drop_index(batch_op.f('ix_investments_symbol'))
        batch_op.drop_index(batch_op.f('ix_investments_twelvedata_id'))

    op.drop_table('investments')
    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platforms_id'))
        batch_op.drop_index(batch_op.f('ix_platforms_name'))

    op.drop_table('platforms')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('auth_provider',
               existing_type=postgresql.ENUM('local', 'google', 'apple', name='authproviderenum'),
               type_=sa.Enum('local', 'google', 'apple', name='authproviderenum', native_enum=False),
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('admin', 'analyst', 'investor', 'support', name='userrole'),
               type_=sa.Enum('admin', 'analyst', 'investor', 'support', name='userrole', native_enum=False),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('role',
               existing_type=sa.Enum('admin', 'analyst', 'investor', 'support', name='userrole', native_enum=False),
               type_=postgresql.ENUM('admin', 'analyst', 'investor', 'support', name='userrole'),
               existing_nullable=False)
        batch_op.alter_column('auth_provider',
               existing_type=sa.Enum('local', 'google', 'apple', name='authproviderenum', native_enum=False),
               type_=postgresql.ENUM('local', 'google', 'apple', name='authproviderenum'),
               existing_nullable=False)

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    op.create_table('platforms',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('platforms_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='platforms_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platforms_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_platforms_id'), ['id'], unique=False)

    op.create_table('investments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('platform_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('asset_type', postgresql.ENUM('crypto', 'stock', 'other', name='assettype'), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('coingecko_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('twelvedata_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('asset_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('invested_amount', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=28, scale=10), autoincrement=False, nullable=False),
    sa.Column('purchase_price', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('date_acquired', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], name=op.f('investments_platform_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('investments_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('investments_pkey'))
    )
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investments_twelvedata_id'), ['twelvedata_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investments_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_investments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investments_coingecko_id'), ['coingecko_id'], unique=False)

    # ### end Alembic commands ###
