"""Add_advanced_portfolio_features

Revision ID: 8a157c245913
Revises: a2f882c5d24b
Create Date: 2025-12-02 01:28:47.687064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a157c245913'
down_revision: Union[str, Sequence[str], None] = 'a2f882c5d24b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crypto_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_crypto_cache'))
        batch_op.drop_index(batch_op.f('idx_crypto_symbol'))

    with op.batch_alter_table('crypto_symbol_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_crypto_mapping_active'))

    with op.batch_alter_table('economic_calendar_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_calendar_country_date'))
        batch_op.drop_index(batch_op.f('idx_calendar_importance'))
        batch_op.drop_index(batch_op.f('idx_calendar_strategy'))

    with op.batch_alter_table('economic_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_economic_cache'))
        batch_op.drop_index(batch_op.f('idx_economic_country'))
        batch_op.drop_index(batch_op.f('idx_economic_frequency'))

    with op.batch_alter_table('performance_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_performance_date'))
        batch_op.drop_index(batch_op.f('idx_performance_drawdown'))
        batch_op.drop_index(batch_op.f('idx_performance_returns'))
        batch_op.drop_index(batch_op.f('idx_performance_risk'))

    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_snapshot_date'))

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_position_symbol_open'))
        batch_op.drop_index(batch_op.f('idx_position_type_open'))

    with op.batch_alter_table('price_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_alert_symbol_active'))
        batch_op.drop_index(batch_op.f('idx_alert_triggered'))

    with op.batch_alter_table('stock_fundamentals_current', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_fundamentals_cache'))

    with op.batch_alter_table('stock_fundamentals_historical', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_historical_fiscal_range'))
        batch_op.drop_index(batch_op.f('idx_historical_symbol_fiscal'))
        batch_op.drop_index(batch_op.f('idx_historical_symbol_period'))

    with op.batch_alter_table('stock_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_stock_cache'))
        batch_op.drop_index(batch_op.f('idx_stock_industry'))
        batch_op.drop_index(batch_op.f('idx_stock_sector'))

    with op.batch_alter_table('technical_indicators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_technical_calculated'))
        batch_op.drop_index(batch_op.f('idx_technical_symbol_type'))

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_trade_action_type'))
        batch_op.drop_index(batch_op.f('idx_trade_platform'))
        batch_op.drop_index(batch_op.f('idx_trade_position_type'))
        batch_op.drop_index(batch_op.f('idx_trade_symbol_date'))

    with op.batch_alter_table('trading_platforms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_platform_active'))
        batch_op.drop_index(batch_op.f('idx_platform_type'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_platforms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_platform_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('idx_platform_active'), ['is_active'], unique=False)

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_trade_symbol_date'), ['symbol', 'trade_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_trade_position_type'), ['position_type', 'trade_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_trade_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('idx_trade_action_type'), ['trade_action', 'trade_date'], unique=False)

    with op.batch_alter_table('technical_indicators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_technical_symbol_type'), ['symbol', 'indicator_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_technical_calculated'), ['calculated_at'], unique=False)

    with op.batch_alter_table('stock_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_stock_sector'), ['sector'], unique=False)
        batch_op.create_index(batch_op.f('idx_stock_industry'), ['industry'], unique=False)
        batch_op.create_index(batch_op.f('idx_stock_cache'), ['cache_until'], unique=False)

    with op.batch_alter_table('stock_fundamentals_historical', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_historical_symbol_period'), ['symbol', 'period_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_historical_symbol_fiscal'), ['symbol', 'fiscal_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_historical_fiscal_range'), ['fiscal_date'], unique=False)

    with op.batch_alter_table('stock_fundamentals_current', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_fundamentals_cache'), ['cache_until'], unique=False)

    with op.batch_alter_table('price_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_alert_triggered'), ['triggered'], unique=False)
        batch_op.create_index(batch_op.f('idx_alert_symbol_active'), ['symbol', 'is_active'], unique=False)

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_position_type_open'), ['position_type', 'is_open'], unique=False)
        batch_op.create_index(batch_op.f('idx_position_symbol_open'), ['symbol', 'is_open'], unique=False)

    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_snapshot_date'), ['snapshot_date'], unique=False)

    with op.batch_alter_table('performance_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_performance_risk'), ['volatility', 'sharpe_ratio'], unique=False)
        batch_op.create_index(batch_op.f('idx_performance_returns'), ['daily_return', 'cumulative_return'], unique=False)
        batch_op.create_index(batch_op.f('idx_performance_drawdown'), ['max_drawdown', 'current_drawdown'], unique=False)
        batch_op.create_index(batch_op.f('idx_performance_date'), ['metric_date'], unique=False)

    with op.batch_alter_table('economic_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_economic_frequency'), ['frequency'], unique=False)
        batch_op.create_index(batch_op.f('idx_economic_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('idx_economic_cache'), ['cache_until'], unique=False)

    with op.batch_alter_table('economic_calendar_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_calendar_strategy'), ['cache_strategy'], unique=False)
        batch_op.create_index(batch_op.f('idx_calendar_importance'), ['importance'], unique=False)
        batch_op.create_index(batch_op.f('idx_calendar_country_date'), ['country', 'event_date'], unique=False)

    with op.batch_alter_table('crypto_symbol_mapping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_crypto_mapping_active'), ['is_active'], unique=False)

    with op.batch_alter_table('crypto_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_crypto_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('idx_crypto_cache'), ['cache_until'], unique=False)

    # ### end Alembic commands ###
