"""add_investment_strategy_and_transaction_date

Revision ID: a2f882c5d24b
Revises: 27b3b194bc5b
Create Date: 2025-11-26 13:11:06.452554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2f882c5d24b'
down_revision: Union[str, Sequence[str], None] = '27b3b194bc5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investments', sa.Column('investment_strategy', sa.String(length=100), nullable=True))
    op.add_column('investments', sa.Column('transaction_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_investments_investment_strategy'), 'investments', ['investment_strategy'], unique=False)
    op.create_index(op.f('ix_investments_transaction_date'), 'investments', ['transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investments_transaction_date'), table_name='investments')
    op.drop_index(op.f('ix_investments_investment_strategy'), table_name='investments')
    op.drop_column('investments', 'transaction_date')
    op.drop_column('investments', 'investment_strategy')
    # ### end Alembic commands ###